<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="rvl_arm" params="
        prefix
        ur_variant
        ur_transmission_hw_interface:=hardware_interface/PositionJointInterface
        robotiq_variant
        robotiq_transmission_hw_interface:=hardware_interface/EffortJointInterface
        safety_limits:=false
        safety_pos_margin:=0.15
        safety_k_position:=20">

        <xacro:property name="coupling_offset" value="0.0053" />
        <xacro:property name="tool_rotation" value="${pi/2}" />
        <xacro:property name="camera_placement_offset" value="0.12439" />
        <xacro:property name="camera_origin_offset" value="0.0061"/>

        <!-- Universal Robots arm -->
        <xacro:include filename="$(find rvl_robot_description)/xacro/universal_robots/include/ur_macro.xacro" />
        <xacro:ur_robot
            prefix="${prefix}"
            variant="${ur_variant}"
            transmission_hw_interface="${ur_transmission_hw_interface}"
            safety_limits="${safety_limits}"
            safety_pos_margin="${safety_pos_margin}"
            safety_k_position="${safety_k_position}" />

        <!-- Custom L515 mounting plate -->
        <xacro:include filename="$(find rvl_robot_description)/xacro/custom/mounting_plate.xacro"/>
        <xacro:L515_mounting_plate prefix="${prefix}"/>
        <joint name="tool0-mounting_plate" type="fixed">
            <parent link= "${prefix}tool0" />
            <child link = "${prefix}L515_mounting_plate" />
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi}" />
        </joint>

        <!-- Robotiq gripper -->
        <xacro:if value="${robotiq_variant.startswith('2f')}">
            <xacro:include filename="$(find rvl_robot_description)/xacro/robotiq/include/robotiq_2f_macro.xacro" />
            <xacro:property name="gripper_height" value="${0.1628 if robotiq_variant[3:] == '85' else 0.2328}" scope="parent"/>
            <xacro:robotiq_2f_gripper
                prefix="${prefix}"
                stroke="${robotiq_variant[3:]}"
                transmission_hw_interface="${robotiq_transmission_hw_interface}"
                parent_link="${prefix}L515_mounting_plate"
                attachment_z="${coupling_offset}"
                attachment_yaw="${tool_rotation}" />
        </xacro:if>

        <xacro:if value="${robotiq_variant == '3f'}">
            <!-- TODO: Add 3-Finger Robotiq model and xacro -->
        </xacro:if>

        <!-- Intel RealSense Camera - TBD -->
        <!-- TODO: Add Intel RealSense L515 (or other variant) support -->

        <!-- Additional link for planning (center of gripper tips when fully closed) -->
        <link name="${prefix}gripper_center_tip" />
        <joint name="${prefix}gripper_center_tip_joint" type="fixed">
            <parent link="${prefix}tool0"/>
            <child link="${prefix}gripper_center_tip"/>
            <origin xyz="0.0 0.0 ${coupling_offset + gripper_height}" rpy="0.0 0.0 0.0"/>
        </joint>

    </xacro:macro>

    <!-- testing -->
    <!-- <xacro:rvl_arm prefix="" ur_variant="ur5e" robotiq_variant="2f_85"/> -->
</robot>