<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ur5e_robotiq_85_gripper">

    <xacro:include filename="$(find unity_robot_description)/xacro/macros/ur5e_macro.xacro" />
    <xacro:include filename="$(find unity_robot_description)/xacro/macros/robotiq_arg2f_85_macro.xacro" />

    <xacro:property name="coupling_offset" value="0.0" />
    <xacro:property name="gripper_height" value="0.1628" />
    <xacro:property name="tool_rotation" value="${pi/2}" />
    
    
    <xacro:macro name="ur5e_with_gripper" params="prefix">
        <!-- Universal Robot UR 5e Arm -->
        <xacro:ur5e_robot prefix="${prefix}"/>

        <!-- Robotiq 2F-85 2-Finger Gripper -->
        <xacro:robotiq_arg2f_85 prefix="${prefix}" />

        <!-- attach gripper to tool0 -->
        <joint name="tool0-gripper_base" type="fixed">
            <parent link= "${prefix}tool0" />
            <child link = "${prefix}robotiq_arg2f_base_link" />
            <origin xyz="0.0 0.0 ${coupling_offset}" rpy="0.0 0.0 ${tool_rotation}" />
        </joint>

        <!-- Add an additional link to plan with. Oriented like the UR ee_link frame. -->
        <link name="${prefix}gripper_center_tip"/>
        <joint name="${prefix}gripper_center_tip_joint" type="fixed">
            <parent link="${prefix}robotiq_arg2f_base_link"/>
            <child link="${prefix}gripper_center_tip"/>
            <origin xyz="0.0 0.0 ${coupling_offset + gripper_height}" rpy="0.0 0.0 0.0"/>
        </joint>
    </xacro:macro>

    <!-- creating the robot -->
    <xacro:ur5e_with_gripper prefix="" />

</robot>