<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="RVL UR3e">

    <!-- TODO: Save dimensions in yaml and load as property -->
    <xacro:property name="tool_rotation" value="${pi/2}" />
    <xacro:property name="coupling_offset" value="0.0053" />
    <!-- <xacro:property name="vertical_offset" value="0.1175" />
    <xacro:property name="camera_thickness" value="0.061" />
    <xacro:property name="camera_placement_xyz" value="0.0 ${camera_thickness/2.0 - vertical_offset} ${0.015 + coupling_offset}" />
    <xacro:property name="camera_placement_rpy" value="${pi/2} ${-pi/2} 0.0" /> -->

    <!-- Universal Robot UR5e -->
    <xacro:include filename="$(find rvl_robot_description)/xacro/universal_robots/include/ur_macro.xacro"/>
    <xacro:ur_robot
        prefix=""
        variant="ur3e"
        transmission_hw_interface="hardware_interface/PositionJointInterface"
        safety_limits="false"
        safety_pos_margin="0.15"
        safety_k_position="20" />

    <!-- Robotiq 2F-85 -->
    <xacro:include filename="$(find rvl_robot_description)/xacro/robotiq/include/robotiq_2f_macro.xacro" />
    <xacro:robotiq_2f_gripper
        prefix=""
        stroke="85"
        transmission_hw_interface="hardware_interface/EffortJointInterface"
        parent_link="tool0"
        attachment_yaw="${pi/2}" />

    <!-- Intel RealSense L515 -->
    <!-- <xacro:include filename="$(find rvl_robot_description)/xacro/realsense/l515.xacro" />
    <xacro:sensor_l515 name="L515" parent="tool0">
        <origin xyz="${camera_placement_xyz}" rpy="${camera_placement_rpy}" />
    </xacro:sensor_l515> -->

    <!-- Custom L515 mounting plate -->
    <!-- <xacro:include filename="$(find rvl_robot_description)/xacro/rvl/mounting_plate.xacro" />
    <xacro:L515_mounting_plate prefix="" />
    <joint name="tool0-mounting_plate" type="fixed">
        <parent link="tool0" />
        <child link="L515_mounting_plate" />
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi}" />
    </joint> -->

    <!-- Additional link for planning (center of gripper tips when fully closed) -->
    <link name="gripper_center_tip" />
    <joint name="gripper_center_tip_joint" type="fixed">
        <parent link="tool0" />
        <child link="gripper_center_tip" />
        <origin xyz="0.0 0.0 ${0.1628 * 0.9}" rpy="0.0 0.0 0.0" />
    </joint>

</robot>