# base_link = palm
# outer_knuckle = knuckle
# outer_finger = bar
# inner_knuckle = proximal_phalanx
# inner_finger = distal_phalanx
# finger_pad = finger_tip

inertial_parameters:
  palm:
    origin:
      xyz: 8.625E-08 -4.6583E-06 0.03145
      rpy: 0 0 0
    mass: 0.22652
    inertia:
      ixx: 0.00020005
      ixy: -4.2442E-10
      ixz: -2.9069E-10
      iyy: 0.00017832
      iyz: -3.4402E-08
      izz: 0.00013478