# base_link = palm
# outer_knuckle = knuckle
# outer_finger = bar
# inner_knuckle = proximal_phalanx
# inner_finger = distal_phalanx
# finger_pad = finger_tip

mesh_files:
  palm:
    visual:
      origin:
        xyz: 0 0 0
        rpy: 0 0 0
      mesh: "package://rvl_robot_description/models/robotiq/2f_85/visual/robotiq_arg2f_base_link.stl"
      scale: 1 1 1
      material:
        name: ""
        color: "0.1 0.1 0.1 1"
    collision:
      origin:
        xyz: 0 0 0
        rpy: 0 0 0
      mesh: "package://rvl_robot_description/models/robotiq/2f_85/collision/robotiq_arg2f_base_link.stl"