# base_link = palm
# outer_knuckle = knuckle
# outer_finger = bar
# inner_knuckle = proximal_phalanx
# inner_finger = distal_phalanx
# finger_pad = finger_tip

link_names:
  palm: &base "robotiq_2f_base_palm"
  knuckle: &knuckle "knuckle_link"
  bar: &bar "bar_link"
  proximal_phalanx: &pphal "proximal_phalanx_link"
  distal_phalanx: &dphal "distal_phalanx_link"
  finger_tip: &tip "finger_tip_link"

joint_names:
  base_to_knuckle: &driven "knuckle_joint"
  base_to_proximal: "proximal_joint"
  knuckle_to_bar: "bar_joint"
  bar_to_distal: "distal_joint"
  distal_to_tip: "tip_joint"

joint_definitions:
  # driven joint
  base_to_knuckle:
    type: "revolute"
    origin:
      xyz: 0 -0.0306011 0.054904
      rpy: 2.295796327 0 0
    parent_link: *base
    child_link: *knuckle
    axis: -1 0 0
    limit:
      lower: 0
      upper: 0.7
      velocity: 0.5
      effort: 1000

  # will prepend "right" to it
  base_to_knuckle_mimic:
    type: "revolute"
    origin:
      xyz: 0 0.0306011 0.054904
      rpy: 2.295796327 0 3.141592654
    parent_link: *base
    child_link: *knuckle
    axis: 1 0 0
    limit:
      lower: -0.725
      upper: 0
      velocity: 0.5
      effort: 1000
    mimic:
      joint: *driven
      multiplier: -1
      offset: 0

  knuckle_to_bar:
    type: "fixed"
    origin:
      xyz: 0 0.01821998610742 0.0260018192872234
      rpy: 0 0 0
    parent_link: *knuckle
    child_link: *bar
    axis: 1 0 0

  bar_to_distal:
    type: "revolute"
    origin:
      xyz: 0 0.0817554015893473 -0.0282203446692936
      rpy: -0.725 0 0
    parent_link: *bar
    child_link: *dphal
    axis: 1 0 0
    limit:
      lower: 0
      upper: 0.8757
      velocity: 0.5
      effort: 1000
    mimic:
      joint: *driven
      multiplier: 1
      offset: 0

  distal_to_tip:
    type: "fixed"
    origin:
      xyz: 0 0.0457554015893473 -0.0272203446692936
      rpy: 0 0 0
    parent_link: *dphal
    child_link: *tip
    axis: 0 0 1

  base_to_proximal:
    type: "revolute"
    origin:
      xyz: "0 ${reflect * -0.0127} 0.06142"
      rpy: "${pi / 2 + .725} 0 ${(reflect - 1) * pi / 2}"
    parent_link: *base
    child_link: *pphal
    axis: 1 0 0
    limit:
      lower: -0.8757
      upper: 0
      velocity: 0.5
      effort: 1000
    mimic:
      joint: *driven
      multiplier: -1
      offset: 0

